### ISSUE TITLE
ArrizalAmin.Portfolio is abandoned

### ISSUE THREAD

**Issue by daftspunk** [PictureElement/rapido-theme#1]
Hi Marios,

This theme appears to depend on an abandoned plugin called `ArrizalAmin.Portfolio` - [link](https://github.com/arrizalamin/october-portfolio)

```
require:
    - ToughDeveloper.ImageResizer
    - RainLab.Blog
    - Rahman.BlogTags
    - PolloZen.MostVisited
    - Tallpro.Related
    - ArrizalAmin.Portfolio
    - JanVince.SmallGDPR
    - Martin.Forms
    - OFFLINE.SiteSearch
```

Currently, it has the following problems:

- Cannot be installed with SQLite

Would you consider removing this dependency, creating your own, or finding a replacement?

Thanks

**Comment by PictureElement** [comment]
Hi Sam and congratulations on the new release. I've installed the theme locally (October v2 release) to resolve the plugin dependency but I've encountered another issue when combining assets.

Specifically:

```
<link href="{{ [
    'assets/sass/rapido.scss'
]|theme }}" rel="stylesheet">
```

Gives the following error:

**An exception has been thrown during the rendering of a template ("`functions` file not found for @import: line: , column: ").**


I figured out that the error is coming from the second ```@import``` statement in ```rapido.scss``` that includes the Bootstrap 4.5 source:
```
@import "settings";
@import "../vendor/bootstrap/scss/bootstrap";               // <====================
@import "global";
@import "header";
@import "hero";
@import "services";
@import "shop";
@import "clients";
@import "projects";
@import "about";
@import "figures";
@import "testimonials";
@import "faqs";
@import "blog";
@import "contact";
@import "footer";
@import "keyframes";
```

Does October CMS fully support Sass? I've encountered similar issues before with the PHP Sass compiler that comes with October.

**Comment by daftspunk** [comment]
Hey @PictureElement thank you!

I have tested your theme and addressed the import issue in this commit:
https://github.com/octobercms/library/commit/cbff57a5dbc0d4166bade099b6d4ba1f8216845e

It should be available by running `composer update`. Please try it again

**Comment by PictureElement** [comment]
@daftspunk Thanks a lot.

**Comment by PictureElement** [comment]
Hi @daftspunk. I've removed this dependency and created my [own](https://octobercms.com/plugin/msof-portfolio). I am in the process of making some final changes/improvements to the theme. I will let you know soon to relist it.

**Comment by daftspunk** [comment]
Sounds good, will keep an eye out for your email

**Comment by PictureElement** [comment]
@daftspunk theme is ready. Could you please take a look and relist it?

**Comment by daftspunk** [comment]
Theme has been relisted. Thanks!
